apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: icmemo-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/cloudsql-instances: PROJECT_ID:REGION:INSTANCE_NAME
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "0"
        run.googleapis.com/cloudsql-instances: PROJECT_ID:REGION:INSTANCE_NAME
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: cloud-run-sql-sa@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - image: gcr.io/PROJECT_ID/icmemo-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-client-id
              key: latest
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-client-secret
              key: latest
        - name: GOOGLE_REDIRECT_URI
          value: "https://icmemo-backend-HASH-uc.a.run.app/api/auth/google/callback"
        - name: FRONTEND_URL
          value: "https://icmemo-frontend-HASH-uc.a.run.app"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: latest
        - name: AFFINITY_API_KEY
          valueFrom:
            secretKeyRef:
              name: affinity-api-key
              key: latest
        - name: PERPLEXITY_API_KEY
          valueFrom:
            secretKeyRef:
              name: perplexity-api-key
              key: latest
        - name: ENVIRONMENT
          value: "production"
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"