"""Add embeddings table for RAG

Revision ID: 45fdb236fa52
Revises: f84bc65b9ac8
Create Date: 2025-10-06 12:10:30.943227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45fdb236fa52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'document_embeddings',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('source_id', sa.Integer(), sa.ForeignKey('sources.id'), nullable=False),
        sa.Column('chunk_text', sa.Text(), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('chunk_type', sa.String(), nullable=False),
        sa.Column('embedding', sa.JSON(), nullable=False),
        sa.Column('sources', sa.JSON()),
        sa.Column('chunk_metadata', sa.JSON()),  # CHANGED FROM 'metadata'
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()')),
    )
    
    op.create_index('ix_document_embeddings_source_id', 'document_embeddings', ['source_id'])
    op.create_index('ix_document_embeddings_category', 'document_embeddings', ['category'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_embeddings_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    # ### end Alembic commands ###