"""Add company_description to sources

Revision ID: bacb40cfc0cf
Revises: 45fdb236fa52
Create Date: 2025-10-06 13:54:42.300728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bacb40cfc0cf'
down_revision: Union[str, None] = '45fdb236fa52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_embeddings_category', table_name='document_embeddings')
    op.drop_index('ix_document_embeddings_source_id', table_name='document_embeddings')
    op.add_column('sources', sa.Column('company_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'company_description')
    op.create_index('ix_document_embeddings_source_id', 'document_embeddings', ['source_id'], unique=False)
    op.create_index('ix_document_embeddings_category', 'document_embeddings', ['category'], unique=False)
    # ### end Alembic commands ###